In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

[2017-07-21 07:20:41,066] Making new env: FrozenLake-v0


In [12]:
rList = [];
num_episodes = 2000;

In [13]:
print("Score over time: " +  str(sum(rList)/num_episodes))#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

Score over time: 0.0


In [15]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.675


In [16]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.28369290e-01   1.52762269e-02   1.58843370e-02   1.49458848e-02]
 [  3.98639773e-03   2.80614529e-03   2.79823510e-03   1.86802311e-01]
 [  2.15311849e-03   3.66559732e-03   6.12800838e-03   1.31824484e-01]
 [  2.24471028e-03   0.00000000e+00   3.80673710e-04   7.42596889e-02]
 [  1.70528898e-01   1.98831271e-03   3.28592500e-03   2.12420887e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.72087030e-04   3.73240514e-05   1.46254337e-01   2.42283746e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.72792325e-04   7.78807340e-04   1.86834904e-04   2.91688251e-01]
 [  6.39365829e-04   3.99835383e-01   6.68266357e-05   9.22663423e-03]
 [  6.10877296e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.96665499e-03   0.00000000e+00   2.38604455e-01   1